// Client-safe: real per-technology brand logos (Simple Icons, via
// react-icons), separate from the generic Lucide `ICONS` map in
// blocks/types.ts — those are abstract UI glyphs, these are actual brand
// marks, so they're kept as their own registry rather than mixed in.
// Every key here was verified to exist in the installed react-icons version
// before use — Simple Icons omits a few real-world logos entirely (Java,
// AWS's own mark) for trademark reasons, so those are sourced from DevIcons
// (AWS) or left out (Java has no available brand icon).

import type { IconType } from "react-icons";
import {
  SiAndroid,
  SiAngular,
  SiCplusplus,
  SiCss,
  SiDart,
  SiDjango,
  SiDocker,
  SiDotnet,
  SiExpress,
  SiFirebase,
  SiFlutter,
  SiGit,
  SiGo,
  SiGooglecloud,
  SiGraphql,
  SiHtml5,
  SiJavascript,
  SiKotlin,
  SiKubernetes,
  SiLaravel,
  SiMongodb,
  SiMysql,
  SiNestjs,
  SiNextdotjs,
  SiNodedotjs,
  SiPhp,
  SiPostgresql,
  SiPython,
  SiReact,
  SiRedis,
  SiSharp,
  SiSwift,
  SiTailwindcss,
  SiTypescript,
  SiVercel,
  SiVuedotjs,
} from "react-icons/si";
import { DiAws } from "react-icons/di";

export const TECH_ICONS = {
  javascript: SiJavascript,
  typescript: SiTypescript,
  python: SiPython,
  php: SiPhp,
  kotlin: SiKotlin,
  swift: SiSwift,
  dart: SiDart,
  go: SiGo,
  csharp: SiSharp,
  cplusplus: SiCplusplus,
  react: SiReact,
  nextjs: SiNextdotjs,
  vuejs: SiVuedotjs,
  angular: SiAngular,
  tailwindcss: SiTailwindcss,
  html5: SiHtml5,
  css: SiCss,
  flutter: SiFlutter,
  android: SiAndroid,
  nodejs: SiNodedotjs,
  express: SiExpress,
  django: SiDjango,
  laravel: SiLaravel,
  dotnet: SiDotnet,
  nestjs: SiNestjs,
  postgresql: SiPostgresql,
  mysql: SiMysql,
  mongodb: SiMongodb,
  redis: SiRedis,
  docker: SiDocker,
  kubernetes: SiKubernetes,
  aws: DiAws,
  googlecloud: SiGooglecloud,
  vercel: SiVercel,
  git: SiGit,
  graphql: SiGraphql,
  firebase: SiFirebase,
} satisfies Record<string, IconType>;

export type TechIconKey = keyof typeof TECH_ICONS;
export const TECH_ICON_KEYS = Object.keys(TECH_ICONS) as TechIconKey[];

export const TECH_ICON_LABELS: Record<TechIconKey, string> = {
  javascript: "JavaScript",
  typescript: "TypeScript",
  python: "Python",
  php: "PHP",
  kotlin: "Kotlin",
  swift: "Swift",
  dart: "Dart",
  go: "Go",
  csharp: "C#",
  cplusplus: "C++",
  react: "React",
  nextjs: "Next.js",
  vuejs: "Vue.js",
  angular: "Angular",
  tailwindcss: "Tailwind CSS",
  html5: "HTML5",
  css: "CSS",
  flutter: "Flutter",
  android: "Android",
  nodejs: "Node.js",
  express: "Express",
  django: "Django",
  laravel: "Laravel",
  dotnet: ".NET",
  nestjs: "NestJS",
  postgresql: "PostgreSQL",
  mysql: "MySQL",
  mongodb: "MongoDB",
  redis: "Redis",
  docker: "Docker",
  kubernetes: "Kubernetes",
  aws: "AWS",
  googlecloud: "Google Cloud",
  vercel: "Vercel",
  git: "Git",
  graphql: "GraphQL",
  firebase: "Firebase",
};
